name: the_weather
description: Simple test app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  linter: ^1.11.0
  path_provider: ^2.0.8
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  go_router: ^4.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CenturyGothic
      fonts:
        - asset: lib/assets/fonts/CenturyGothic.ttf
        - asset: lib/assets/fonts/CenturyGothic-Bold.ttf
          weight: 700

  assets:
    - .env
